services:
  database:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_TENANTS: "standalone,symfony"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 2345:5432
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./docker/setup-tenants.sh:/docker-entrypoint-initdb.d/setup-tenants.sh
